[env]
RUST_ESP32_STD_DEMO_WIFI_SSID = "Devins hotspot"
RUST_ESP32_STD_DEMO_WIFI_PASS = "eeeeeeee"

[tasks.default]
dependencies = ["build"]

[tasks.toolchain-init]
command = "./toolchain-deps/init-toolchain.sh"

[tasks.toolchain-env]
command = "./toolchain-deps/env-toolchain.sh"
dependencies = ["toolchain-init"]

[tasks.build]
env_files = [ "./toolchain-deps/espressif.env" ]
command = "cargo"
args = ["+esp", "build"]
dependencies = ["toolchain-env"]

[tasks.flash]
install_crate = "espflash"
command = "espflash"
args = ["/dev/ttyUSB0", "target/xtensa-esp32-espidf/debug/esp32"]
dependencies = ["build"]

[tasks.run]
command = "cargo"
args = ["+esp", "pio", "espidf", "monitor", "/dev/ttyUSB0"]
dependencies = ["build", "flash"]

[tasks.test]
# Note: tests may not be possible, or even required
#       they would be nice, but I'm pretty sure we'd have to do some mixed-platform stuff
disabled = true