[tasks.default]
dependencies = ["build"]

[tasks.toolchain-init]
command = "./toolchain-deps/init-toolchain.sh"

[tasks.toolchain-env]
command = "./toolchain-deps/env-toolchain.sh"
dependencies = ["toolchain-init"]

[tasks.run]
command = "cargo"
args = ["+esp", "espflash", "--monitor", "/dev/ttyUSB0"]
dependencies = ["build"]

[tasks.build]
env_files = [
          "./toolchain-deps/espressif.env"
]
command = "cargo"
args = ["+esp", "build"]
dependencies = ["toolchain-env"]
